### ISSUE TITLE
🚨 🚨 [HIGH PRIORITY] - User Should be able to Search for a Flight

### ISSUE THREAD

**Issue by chill5018** [chill5018/FlightApp-api#27]
We need to be able to send a query to the API where the Client can query a list of available flights using the following query params: 

GET `/flights?departureCity="Copenhagen"&arrivalCity="New York City"&departureDate="21/12/2018"&returnDate="21/12/2018`

**Comment by burasDiana** [comment]
I'll do it tonight or tomorrow in class
